apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z5xjqw6ou-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:b27ef61f45117116dda95576211536fae659811f@sha256:7c82fb251c9276e1eb9eac29694561c1aaa8cfa02c3bc2232a9a94c59cbeabdb
          name: container-image
